### ISSUE TITLE
Cache dependency for this proxy

### ISSUE THREAD

**Issue by festeh** [proofit404/dependencies#298]
Hi!
Is is possilble to not recompute a dependency when using `this` proxy?
 Here's a dummy example just to illustrate
```
from dependencies import Injector
from dependencies import this


class WannaBeSingleton:
    def __init__(self):
        self.value = 1
        print("Called")


class Dummy:
    def __init__(self, singleton, value):
        pass


class Container(Injector):
    singleton = WannaBeSingleton
    value = this.singleton.value
    dummy = Dummy


if __name__ == '__main__':
    d = Container.dummy
```
It will output `Called` twice. I expected that `this.singleton` would already be cached when `value` is computed.

While this example is trivial to fix, in the actual project it would be complicated. So I'd want to know if one could make `this` aware of already computed dependencies. Thanks!

**Comment by proofit404** [comment]
Maybe value decorator will be useful for you?
```python
from functools import lru_cache
from dependencies import Injector, value

class Container(Injector):
    dummy = Dummy

    @value
    @lru_cache
    def singleton(value):
        return WannaBeSingleton(value)
```

**Comment by festeh** [comment]
Yes, this is a pretty out-of-box thinking solution. Thanks!
