### ISSUE TITLE
this.let support

### ISSUE THREAD

**Issue by volcacius** [proofit404/dependencies#300]
Hello,

First, thanks a lot for your work, this is such a good library.
Second, I was wondering if there is any way to support this kind of pattern:

```python
class Baz:

    def __init__(self, foo):
        self.foo = foo

    def __call__(self):
        print(self.foo)

class Container(Injector):
    foo = 1
    bar = this.let(foo=2).baz
    baz = Baz

Container.baz() // prints 1
Container.bar() // prints 2
```

Thanks a mil

Alessandro

**Comment by proofit404** [comment]
Hi, thanks for trying the library :tada: 

Some kind of namespaces could be created with nested injectors + this proxy:

```python
class Container(Injector):
    foo = 1
    bar = this.Bar.baz
    baz = Baz

    class Bar(Injector):
        baz = (this << 1).baz
        foo=2

Container.baz() # prints 1
Container.bar() # prints 2
```

Here is a full example: https://proofit404.github.io/dependencies/proxies/this/#full-example

I agree this is not the shortest possible way to express things but it works :slightly_smiling_face: 

I would think about your proposal with `this.let` notation. It looks promising but could be tricky to implement. Also, I maybe need to experiment with `Injector.let` for the same stuff you have addressed.

```python
class Container(Injector):
    foo = 1
    bar = this.Bar.baz
    baz = Baz
    Bar = Injector.let(baz=(this << 1).baz, foo=2)
```

Have a good day :palm_tree: 

Best regards,
Artem.

P.S. it's midnight for me, the code examples may not work out of the box. Feel free to reopen if you have any further questions.
