### ISSUE TITLE
How to - instantiate third party libs that use kwargs

### ISSUE THREAD

**Issue by morganics** [proofit404/dependencies#423]
Hello - 

I have two questions - I quite like the model where there's a config object, which you can call in the setup, e.g.

Config.from_env().from_params(args) 

Which would work fine if attached to a container. However, I'm creating singletons using the @value for some third party libraries, e.g. in the container;

```python
    @value
    def account_url(config):
        return "https://{}.blob.core.windows.net/".format(config.AzureBlobUri)

    @value
    def vault_url(config):
        return "https://{}.vault.azure.net".format(config.AzureKeyVaultUri)

    @value
    def credential():
        return DefaultAzureCredential()

    @value
    def blob_service_client(account_url, credential):
        return BlobServiceClient(account_url=account_url, credential=credential)
```

Maybe there is a better way of instantiating third party classes that use kwargs? Or, should I just create my Config object and then use the Scope to assign it to the scoped container?

Thanks.

**Comment by proofit404** [comment]
Hello, thank you for using this library!

Usually, I follow @value decorator convention.

```python
class Container(Injector):
    @value
    def foo(bar, baz):
        return ClassWithKwargs(bar=bar, baz=baz)
```

It does work, but maybe it's not the most elegant solution.

Maybe we should add something to reduce the boilerplate

```python
from dependencies import shield  # does not exists yet

class Container(Injector):
    foo = shield(ClassWithKwargs, 'x', 'y')
    x = 1
    y = 2

Container.foo # will pas x and y to the class **kwargs
```
What do you think about design like that?

**Comment by proofit404** [comment]
cc @supadrupa @anatoly-scherbakov @ditansu

**Comment by morganics** [comment]
Hi - to be honest the @value decorator is probably enough - and seems to be what I'm doing currently. However, it is only called once, so it might also be good to have a @factory decorator or similar which creates an instance every time.

In which case; what is the best way of using external config, without using os.environ etc. My code looks like this at the moment;

```python
config = Config()
config.from_env().from_dict(req.params)
scope = c.Container(config=config)    
scope.turbo.calculate()
```
because if I use;

```python
c.Container.config.from_env().from_dict(req.params)
c.Container.turbo.calculate()
```
My env variables aren't populated in the object. 

The 'config' object is inspired by the dependency-injector Python lib which was ok but I didn't like peppering existing code with 'Provide' syntax. Perhaps some sort of 'startup' function on the Container type? Or maybe I'm doing it wrong!

**Comment by proofit404** [comment]
@morganics you can take a look at https://github.com/proofit404/dependencies/pull/425 to see an example of correct environment variable usage.

HTTP request details could be passed to the config via constructor too.

```python
Container(**req.params).turbo.calculate()
```

The trick here that you should remove `from_dict` and `from_env` methods from the config class.

**Comment by morganics** [comment]
Makes sense - I like the instantiation of the Config object. Apologies for the questions - but what about missing, optional vars? Required vars will die with a keyerror, which is ok. Obviously, I could do the work outside the container, but I think it's better for the config object to handle it. I've got another question but I'll raise a different issue.

**Comment by proofit404** [comment]
If you have environment variable which could be set or not, you can use `@value` object as we did earlier:

```python
@value
def service_url(environ):
    return environ.get('SERVICE_URL', 'default_value')
```

**Comment by proofit404** [comment]
I think we answered all unknowns in this question.

Feel free to reopen if needed.

Regards,
Artem.
