### ISSUE TITLE
Returning a class from @value

### ISSUE THREAD

**Issue by volcacius** [proofit404/dependencies#454]
Hello,

I'm wondering if returning a class to instantiate from a @value function is not supported or I'm just getting the syntax wrong somehow. Very contrived example that I thought would print 8 but gives an error:

```python
from dependencies import value, Injector

class FooImpl1:

    def __init__(self, baz):
        self.baz_prod = baz


class FooImpl2:

    def __init__(self, baz):
        self.baz_prod = baz * 2


class Inject(Injector):
    baz = 4
    name = 'foo2'

    @value
    def foo(name):
        if name == 'foo1':
            return FooImpl1
        elif name == 'foo2':
            return FooImpl2
        else:
            raise RuntimeError("Foo not found")

print(Inject.foo.baz_prod)
```

Thanks

Alessandro

**Comment by proofit404** [comment]
I added explanation of the `@value` object in linked pull request. Please, give me feedback if it explain the concept better.

In your case, it's not possible to instantiate class after `@value` object was evaluated.

As a workaround you may instantiate both classes as value object dependency, and then decide what instance return.

```python
from dataclassess import dataclass
from dependencies import value, Injector

@dataclass
class FooImpl1:
    baz: int

@dataclass
class FooImpl2:
    baz: int

class Inject(Injector):
    @value
    def foo(name, foo1, foo2):
        if name == 'foo1':
            return foo1
        elif name == 'foo2':
            return foo2
        else:
            raise RuntimeError("Foo not found")
   
    name = 'foo2'
    foo1 = FooImpl1
    foo2 = FooImpl2
    baz = 4

print(Inject.foo.baz)
```

**Comment by proofit404** [comment]
Maybe [Shield object](https://github.com/proofit404/dependencies/milestone/10) would be able to solve this in more elegant way if we allow to use it as a decorator.

I'm not sure if that much complexity is worth adding.

**Comment by volcacius** [comment]
Hello,

Thanks for the explanation. I would maybe make more explicit that if `@value` returns a class, it is treated as is, rather than being another object to instantiate. In my mind I thought that `@value` is similar to `@property` in the way that you can define an attribute through code, but actually the comparison breaks down once you return a class.

I agree that adding another decorator is too much complexity also from a user point of view. If anything I'd try to make `@value` work the same way as attributes of Injector currently work, meaning that `def foo_class(name):` should return `FooImpl2`, while `def foo(name)` should return `FooImpl2(baz)`, but I'm not sure how that could work implementation-wise.

Alessandro

**Comment by proofit404** [comment]
Do you think we need to force `foo_class` name restriction, if value object returns a class rather than instance?

**Comment by volcacius** [comment]
To me it would make sense with respect to how the rest of the library works. For example in the simplest case if I just look at the code below:

```python

from dataclassess import dataclass
from dependencies import value, Injector

@dataclass
class Foo:
    baz: int

class Inject(Injector):
    
    @value
    def foo():
        return Foo

    @value
    def foo_class():
        return Foo

    bar_class = Foo
    bar = Foo
    baz = 4
```

I would expect `Inject.foo` to behave like `Inject.bar`, but instead it behaves like `Inject.foo_class` and `Inject.bar_class`. I think it would be an elegant way to allow for more dynamic behaviour while reusing the current available syntax.

**Comment by proofit404** [comment]
> I would maybe make more explicit that if @value returns a class, it is treated as is, rather than being another object to instantiate.

Fixed. Thanks for suggestion!

**Comment by proofit404** [comment]
I merged documentation fixes. We could continue our discussion in the follow up issue I created for the class-named attribute restriction.

**Comment by volcacius** [comment]
Great thanks!
