### ISSUE TITLE
Code claimed to be DI without dependencies is not DI at all

### ISSUE THREAD

**Issue by metaperl** [proofit404/dependencies#499]
In the README we read:

Dependency injection without `dependencies`

```pycon

>>> from app.robot import Robot, Servo, Amplifier, Controller, Settings

>>> robot = Robot(
...     servo=Servo(amplifier=Amplifier()),
...     controller=Controller(),
...     settings=Settings(environment="production"),
... )

>>> robot.work()

```

But this is an example of code that lacks any DI whatsoever.

Here is an example of DI without the dependencies module:

```python

from app.robot import Robot, Servo, Amplifier, Controller, Settings

@dataclass
class Robot:
    
    servo: Servo
    controller: Controller
    settings: Settings 
    

def inject():
    robot = Robot(
        servo=Servo(amplifier=Amplifier()),
        controller=Controller(),
        settings=Settings(environment="production")
        )

```

**Comment by proofit404** [comment]
Hi, thanks for the feedback!

> But this is an example of code that lacks any DI whatsoever.

Could you elaborate more on this statement?

If I read second code example correctly, the only difference here is that it was wrapped in to `inject` function.

But the concept of IoC via constructor stays the same.

Have a good day 🌴🥥

Regards, 
Artem

**Comment by proofit404** [comment]
Feel free to reopen if this is still an issue.
