### ISSUE TITLE
Pdoc breaks with Injector

### ISSUE THREAD

**Issue by MaenMallah** [proofit404/dependencies#531]
Hello again,

I am trying to generate a documentation from Docstrings using pdoc3 and it breaks when using the Injector. 

In this example only class one is documented and not class two
```python
from dependencies import Injector
from dependencies import this
import inspect

class one:
    """test without Injector"""

class two(Injector):
    """test with Injector"""

##inspect.unwrap(this)

```

Additionally, if I use this anywhere the the documentation breaks - at some point it tries inspect.unwrap(this) and it seems to get stuck in an infinite loop as this wraps itself? I can get around this problem by blacklisting it to pdoc but anyway just inheriting from the extended Injector breaks the documentation generation. Is there anyway around this?

**Comment by 0xbeefc0de** [comment]
That's not a bug in Dependencies, that's a bug in pdoc3. It works fine with Sphinx or pdoc.

**Comment by proofit404** [comment]
Good evening,

Do we speak about [pdoc](https://github.com/pdoc3/pdoc) or [pdocs](https://github.com/timothycrosley/pdocs)?

**Comment by 0xbeefc0de** [comment]
That was quick, thank you @proofit404! 🍰 

FWIW there's [pdoc](https://pdoc.dev/), [pdoc3](https://github.com/pdoc3/pdoc) and [pdocs](https://github.com/timothycrosley/pdocs). pdoc is not the same as pdoc3, see https://github.com/mitmproxy/pdoc#pdoc-vs-pdoc3.

**Comment by MaenMallah** [comment]
Thanks for the quick reply and fix @proofit404

@0xbeefc0de, thanks I didn't know this info. I switched now to pdoc.
