### ISSUE TITLE
how to deal with name clashes?

### ISSUE THREAD

**Issue by s22chan** [proofit404/dependencies#534]
Is there an easy way to accommodate classes that require different instances but have the same arg name. For example if I require different loggers for A and B:
```python
class A:
    def __init__(self, logger):
        self.logger = logger

class B:
    def __init__(self, logger):
        self.logger = logger
```

I currently put these in separate Injectors, but if I later have an upper object that composes them, there will be a name clash on `logger`. Nested injectors can work (and allows me to select what to share/not share between A/B), but then I cannot create these objects directly from the Root container (since `this` aliases and `@value` wrappers are only for subdependencies.)
```python
class Root(Injector):
   c = C
   a = this.A.a
   b = this.B.b

   class A(Injector):
       a = A
       logger = ...
```

Perhaps it would be useful to have something that can wrap a `this` or `@value` to declaratively to say it can also be used directly (although it might then be abused)

**Comment by proofit404** [comment]
You're right. At the moment you can't create a variant of `Root` injector which would allow to build `a`, `b`, and `c` at the same time and have unique `logger` for each of them.

A proposed [Puck object](https://github.com/proofit404/dependencies/milestone/15) would allow such configuration, but it does not exists yet.

```python
from dependencies import Injector, pluck, this

class Root(Injector):
    c = C
    a = pluck(A, logger=this.a_logger)
    b = pluck(B, logger=this.b_logger)
    a_logger = ...
    b_logger = ...  # Could be nested Injector as well
```
```pycon
>>> Root.c
C(A(Logger(name='a')), B(Logger(name='b')))

>>> Root.a
A(Logger(name='a'))

>>> Root.b
B(Logger(name='b'))
```

If this solution would serve your needs, I propose to collaborate on this milestone. We could work together with you in small iterations (pull requests targeting `develop` branch). Each merged pull request would be published as `rc` version on PyPI automatically, so you would be able to test it in prod asap. If you would like to try, just let me know :smile: 

***

Just to solve your problem with less elegant solution:

```python
class ContainerA(Injector):
    a = A
    logger = Logger
    name = 'a'

class ContainerB(Injector):
    b = B
    logger = Logger
    name = 'b'

class ContainerC(Injector):
    c = C
    a = this.A.a
    b = this.B.b
    A = ContainerA
    B = ContainerB
```
```pycon
>>> ContainerA.a
>>> ContainerB.b
>>> ContainerC.c
```
You have to use different top level injectors in different cases, but it should works.

**Comment by proofit404** [comment]
Hope it helps, feel free to reopen if you have more questions.

Best regards,
Artem.
