### ISSUE TITLE
injection of a dynamic class

### ISSUE THREAD

**Issue by GuySuday** [proofit404/dependencies#537]
Given a class known at runtime (dynamic) with dependencies in the c'tor, can we use the container to initialize such class?

E.g: 
```python
from dependencies import Injector

class Person:
    def __init__(self, name: str):
        pass

def get_cls():
    return Person

class Container(Injector):  # (1)
    ...
    # (2)

# (3)
person = ...  # (4)
```

1. I tried to inherit from more classes, but got an exception: `_dependencies.exceptions.DependencyError: Multiple inheritance is allowed for Injector subclasses only`
2. I tried to use `__new__` but with no luck
3. I tried to register a class variable after the class definition, but got an exception: `_dependencies.exceptions.DependencyError: 'Injector' modification is not allowed`

Is there away to create such dynamic behavior? Or is it inevitable becuase of the nature of the simplified and non-boilerplate API?

@proofit404  Looking forward to hear your opinion :)

**Comment by proofit404** [comment]
Maybe [@value decorator](https://proofit404.github.io/dependencies/value/) would help?

**Comment by GuySuday** [comment]
Thank you for the answer.

I tried to use the decorator, but I still encounter the following problem: I need the dynamic classes to be instantiated with the dependencies, but I don't know the classes beforehand (and especially not their dependencies).

In my dummy example I need to instantiate `Person('hello')` and  `Animal(5)`, but I'm still missing something.

```python
from dataclasses import dataclass
from typing import List, Type

from dependencies import Injector, value

class Person:
    def __init__(self, name: str):
        self.name = name

class Animal:
    def __init__(self, age: int):
        self.age = age

def get_plugin_classes() -> List[Type]:
    return [Person, Animal]


@dataclass
class Plugins:
    plugins_lst: List[Type]


class Container(Injector):
    name = 'hello'
    age = 5
    plugins = Plugins

    @value
    def plugins_lst() -> List[Type]:
        return get_plugin_classes()

# TODO: how do we instantiate the classes? We need Person('hello') and Animal(5)
classes_to_instantiate = Container.plugins.plugins_lst
```

Appreciate your help :)

**Comment by GuySuday** [comment]
Thank you for thw answer.

The problem is that we don't know the plugins (e.g person, animal) until runtime, so we can't use them explicitly in Container.

What do you think?

**Comment by GuySuday** [comment]
> You could create a mapping of plugin type to the `Injector` subclass.
> 
> ```python
> class Container(Injector):
>     plugins = Plugins
> 
>     @value
>     def plugins_lst():
>         lookup = {type(person): PersonContainer, type(animal): AnimalContainer}
>         return [lookup[each].plugin for each in get_plugin_classes()]
> 
> 
> class PersonContainer(Injector):
>     plugin = Person
>     name = 'hello'
> 
> 
> class AnimalContainer(Injector):
>     plugin = Animal
>     age = 5
> ```
> That way you don't need to instantiate all possible variants of plugins before `get_plugin_classes` would be called.
> 
> The downside of this solution that `Container`, `PersonContainer` and `AnimalContainer` can't share same instances of dependencies with the same name. It could be a problem if it is for connection pool or asyncio event loop. There is a workaround for that in `@value`.
> 
> ```python
> class Container(Injector):
>     plugins = Plugins  # Depends on `connection_pool`.
>     connection_pool = Pool 
> 
>     @value
>     def plugins_lst(connection_pool):
>         lookup = {type(person): PersonContainer, type(animal): AnimalContainer}
>         return [lookup[each](connection_pool=connection_pool).plugin for each in get_plugin_classes()]
> 
> 
> class PersonContainer(Injector):
>     plugin = Person  # Depends on `connection_pool`.
>     name = 'hello'
> 
> 
> class AnimalContainer(Injector):
>     plugin = Animal  # Depends on `connection_pool`.
>     age = 5
> ```
> 

The problem is I don't know what get_plugin_classes will return. I just know it will be a list of classes that want to be a part or the dependencies container, in order to be dynamically dependent on them.
So in your example, I can't create both PersonContainer and AnimalContainer, as I don't know about the existence of both Person or Animal

**Comment by proofit404** [comment]
```pycon
>>> from dependencies import Injector
>>> from dataclasses import dataclass
>>> @dataclass
... class Person:
...     name: str
...
>>> @dataclass
... class Animal:
...     age: int
...
>>> def get_plugin_classes():
...     return [Person, Animal]
...
>>> @dataclass
... class Plugins:
...     plugins_lst: ...
...
>>> class AllDeps(Injector):
...     name = 'hello'
...     age = 5
...
>>> class Container(Injector):
...     plugins = Plugins
...
>>> Container(plugins_lst=[AllDeps(plugin=plugin).plugin for plugin in get_plugin_classes()]).plugins
Plugins(plugins_lst=[Person(name='hello'), Animal(age=5)])
```
We could try something like this.

It still requires you to know names of possible dependencies for all classes which could be returned from `get_plugin_classes`.

What do you think?

**Comment by GuySuday** [comment]
Looks very good, thank you for your help! :)

**Comment by proofit404** [comment]
Feel free to reopen this issue if you have further questions.

Have a good day :palm_tree: :cocktail: 

Best regards,
Artem.
