### ISSUE TITLE
Any example on how to integrate with Pytest?

### ISSUE THREAD

**Issue by jonathanmach** [proofit404/dependencies#555]
Hi 👋
I came across this library here: https://github.com/alecthomas/injector/issues/114#issuecomment-522722345, when trying to figure out how to use Injector with Pytest.
There it's mentioned:
> We already have [integration with pytest suite](https://dependencies.readthedocs.io/en/latest/contrib/pytest/).

But the link seems to be broken – is there an updated link for that source?

Thank you! 🙏

**Comment by proofit404** [comment]
Good afternoon,

Around two years ago I came to conclusion that framework integrations are not worth it #192 

In case of dependencies there was a syntax sugar to create a pytest fixture from `Injector` subclass.

```python
@fixture
class CreateTestUser(CreateUser):
    name = 'create_user`
    fixture = this.create
    send_sms = require('mock_sms_send')
    send_email = require('mock_email_send')
```
Which was exact equivalent for:
```python
@pytest.fixture
def create_user(mock_sms_send, mock_email_send):
    return CreateUser(send_sms=mock_sms_send, send_email=mock_email_send).create
```
As you can see, there is no much value to have something like that.

Integrations with framework depends heavily on architecture of your application.

Pure DDD with Commands, Aggregates and Entities integrates with testing framework differently from Use Cases and Adapters from clean architecture.

`dependencies` library is just a glue which holds it together.

If you explain what your code looks like outside of testing framework I could try to help you what your tests should look like.

Hove a good day :palm_tree: :cocktail: 

Regards,
Josiah.

**Comment by jonathanmach** [comment]
Hi @proofit404, good evening! I hope you're doing well 🙏 
Thanks so much for your response.

I'm exploring a very simple case, here's a basic example of what I'm trying to accomplish:
(I know the user registration logic could be extracted and moved into its own service, but this is just an example)
```python
# rest/registration.py
from external import ServicesContainer
users_api = Blueprint("users_api", __name__)

@users_api.route("/registration", methods=["POST"])
def register_new_user():
    # TODO: Implement registration
    # ...

    # Notifier
    notifier = ServicesContainer.notification
    notifier.notify({"message": "New user registered"})

    return "", 201


# services/notification.py
class NotificationService():
    def __init__(self) -> None:
        pass
        
    def notify(self, data: dict):
        print("Notifying...")


# external/__init__.py
from dependencies import Injector
class ServicesContainer(Injector):
    notification = NotificationService
```

This is working fine (although I'm curious to know if this is how you would implement such use case).
Now imagine I have several services and dozens of endpoints.
During tests, I would like to completely swap my `ServicesContainer`  for a `TestServicesContainer`  that uses Fake implementations of my services instead.

I'm sure it's a use case you've encountered before and would love if you could share how you would tackle this scenario.
Thank you in advance 🙏

**Comment by proofit404** [comment]
Hello :wave:,

I follow one simple rule in that case.

    Views should not hard code Injector they use.

To avoid coupling between modules we could use tools that framework provides.

For example, your view could look like this:

```python
from flask import Blueprint, current_app

users_api = Blueprint("users_api", __name__)

@users_api.route("/registration", methods=["POST"])
def register_new_user():
    containers = current_app.config['CONTAINERS']
    containers.ServicesContainer.notification.send({"message": "New user registered"})
    return "", 201
```

Your application should load different configuration python modules in tests and in production.

```python
app.config.from_object('app.test_settings')
```

In both cases we could import different containers module under the same name.

```python
# production settings
from app import containers as CONTAINERS
```
```python
# test settings
from tests import fake_containers as CONTAINERS
```

That way your view would access different notification class instances in different contexts.

To be honest, I'm too lazy for that so I would rather go and save containers module right into `g` object in some pytest fixture with autouse set to True and scope equals session.

Hope that helps,

Best regards,
Josiah.

**Comment by proofit404** [comment]
If you're using containers heavily in your app, for example every celery task and flask view touch it, it maybe worth to create your own context local variable. See https://github.com/pallets/flask/blob/main/src/flask/globals.py#L54

```python
from app import containers

@blueprint.route("/")
def home():
    containers.Home.show()
```

**Comment by jonathanmach** [comment]
Thanks very much, @proofit404!

After some research, I think I'm after something like [FlaskInject](https://github.com/alecthomas/flask_injector#example-application-using-flask-injector), so that I could have any dependencies explicitly injected into my views:

```python
@users_api.route("/registration", methods=["POST"])
def register_new_user(notifier: NotificationService):
    notifier.notify({"message": "New user registered"})
    return "", 201
```

I had a look on how [FlaskInject is implemented](https://github.com/alecthomas/flask_injector/blob/master/flask_injector/__init__.py) and was planning to have a go in implementing something similar for Dependencies.
Let me know if you think this is bad idea 🤔 

Thanks very much for your support!

**Comment by proofit404** [comment]
View layer of my applications is thin usually, so it does not need configuration like that. So, I don't know if this is a good or bad idea in your context.
