### ISSUE TITLE
"'value' dependencies could only be used to instantiate classes" when returning classes

### ISSUE THREAD

**Issue by morganics** [proofit404/dependencies#557]
I'm using the following code with a simple test container:

```python
class SimpleContainer(Injector):
    
    blob_account_url = "my_blob_url"

    @value
    def blob_service_client(blob_account_url):
        return BlobServiceClient(account_url=blob_account_url, 
                            credential=AzureCliCredential())

    @value
    def blob_service(blob_service_client, blob_account_url):
        return BlobService(blob_service_client, blob_account_url)
```

```python
def test_simple_container(self):
        assert SimpleContainer.blob_service is not None
```

Gives the error "'value' dependencies could only be used to instantiate classes" when returning classes". As far as I can tell, only classes are being returned from the value methods. Commenting out the exception in Spec.py gives the expected result (no exception).

**Comment by proofit404** [comment]
Hello, thank you for using `dependencies` library!

The purpose of `@value` object is evaluate constructor argument value during dependency injection process. Also, `@value` objects could be used to manage setup and teardown process of dependencies of the class you need.

You could touch attributes of the injector subclass if it define class directly or `Package` object which would point into a class.

Your example could be rewritten in more elegant way without `@value` objects at all.

```python
class SimpleContainer(Injector):
    blob_service = BlobService
    blob_service_client = BlobServiceClient
    account_url = "my_blob_url"
    credential = AzureCliCredential

assert SimpleContainer.blob_service is not None
```

Hope that helps, feel free to reopen if you have more questions.

Have a good day :palm_tree: :cocktail: 

Best regards,
Josiah.
