### ISSUE TITLE
How to use configuration file?

### ISSUE THREAD

**Issue by satyamjay-iitd** [proofit404/dependencies#569]
Can you please provide an example of how to correctly use a configuration file with this library?
```
class Scope(Injector):
    foo = Foo
    one = Bar
    two = Baz
    x = 1
```
For example, what if I dont want to hardcode x=1 above rather read it from a config file. What would be the correct way to do it?

**Comment by proofit404** [comment]
Hello,

I hope you would find useful `dependencies` library.

I wrote a little article explaining answer to your question: https://proofit404.github.io/dependencies/settings/

If you have more questions (even for the same topic), feel free to file new issue.

Have a great weekend :palm_tree: :cocktail: 

Best regards,
Josiah.

**Comment by satyamjay-iitd** [comment]
Thank you very much.
