### ISSUE TITLE
How to build/read documentation?

### ISSUE THREAD

**Issue by julian-goettingen** [proofit404/dependencies#587]
this seems like a silly question, but I am not very experienced in python packaging/distribution.

There are a bunch of markdown-files in the doc-folder and I would like to read them in order.
I cannot find them hosted on a site like readthedocs.
$ py -m mkdocs serve
I see there is a mkdocs.yml, so I tried building the docs with mkdocs serve. I am getting the error:
ERROR    -  Config value 'theme': Unrecognised theme name: 'material'. The available installed themes are: mkdocs, readthedocs
ERROR    -  Config value 'markdown_extensions': Failed to load extension 'pymdownx.magiclink'.
            ModuleNotFoundError: No module named 'pymdownx'
Aborted with 2 Configuration Errors!

Trying to install pymdownx is unsuccessful:
$ pip3 install --user pymdownx
ERROR: Could not find a version that satisfies the requirement pymdownx (from versions: none)
ERROR: No matching distribution found for pymdownx

**Comment by proofit404** [comment]
Hello, thanks for trying `dependencies` library.

At the moment our build pipeline does not support release and develop documentation at the same time. Which is sucks, I know.

I would suggest 
1. Clone the repo
2. run ./scripts/install
3. run ./scripts/serve

As a quick fix.

Hope that helps.

Have a nice day :palm_tree: :cocktail: 

Regards,
Josiah.

**Comment by julian-goettingen** [comment]
Thanks for the explanation. Sorry I didn't respond earlier, I have somehow missed it.
